import { CorrespondenceCommentsDetail } from './correspondence-details-comments.model';
export const CORRESPONDENCEDETAILCOMMENTS: CorrespondenceCommentsDetail[] = [
    {
        actualRows: 3,
        filteredRows: 3,
        myRows: [
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: true,
            cmmentReplay : [
              {
                ID: 39833,
                Version: 1,
                Deleted: 0,
                CurrentVer: 1,
                CreationDate: "2019/04/22 11:26:54",
                CreatorID: 2866736,
                ReplyTo: 39831,
                CommentText: "The passage is attributed to an unknown typesetter in the 15th century who is thought",
                ReferenceID: 94482725,
                ReferenceType: "Workflow",
                Private: 0,
                TaskID: 9,
                Task_IterNum: 2,
                CreatorName_EN: "Angeline Mazala Ablaza",
                CreatorName_AR:" Angeline Manzala Ablaza",
                shortComment: "Noted. ",
                ReplyAvailable: true,
                cmmentReplay : [{
                  ID: 39833,
                  Version: 1,
                  Deleted: 0,
                  CurrentVer: 1,
                  CreationDate: "2019/04/22 11:26:54",
                  CreatorID: 2866736,
                  ReplyTo: 39831,
                  CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs.",
                  ReferenceID: 94482725,
                  ReferenceType: "Workflow",
                  Private: 0,
                  TaskID: 9,
                  Task_IterNum: 2,
                  CreatorName_EN: "Angeline Mazala Ablaza",
                  CreatorName_AR:" Angeline Manzala Ablaza",
                  shortComment: "Noted. ",
                  ReplyAvailable: true,
                  cmmentReplay : [{
                    
                  }]
                }]
              },
              {
                ID: 39833,
                Version: 1,
                Deleted: 0,
                CurrentVer: 1,
                CreationDate: "2019/04/22 11:26:54",
                CreatorID: 2866736,
                ReplyTo: 39831,
                CommentText: "The passage is attributed to an unknown typesetter in the 15th century who is thought",
                ReferenceID: 94482725,
                ReferenceType: "Workflow",
                Private: 0,
                TaskID: 9,
                Task_IterNum: 2,
                CreatorName_EN: "Angeline Mazala Ablaza",
                CreatorName_AR:" Angeline Manzala Ablaza",
                shortComment: "Noted. ",
                ReplyAvailable: false
              }
            ]
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
          {
            ID: 39833,
            Version: 1,
            Deleted: 0,
            CurrentVer: 1,
            CreationDate: "2019/04/22 11:26:54",
            CreatorID: 2866736,
            ReplyTo: 39831,
            CommentText: "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
            ReferenceID: 94482725,
            ReferenceType: "Workflow",
            Private: 0,
            TaskID: 9,
            Task_IterNum: 2,
            CreatorName_EN: "Angeline Mazala Ablaza",
            CreatorName_AR:" Angeline Manzala Ablaza",
            shortComment: "Noted. ",
            ReplyAvailable: false,
          },
        ],
        sourceID: 8043162,
        success: true,
        totalRows: 3,
        totalSourceRows: 3
      }
]
