import { CorrespondenceAttachmentsDetail } from './correspondence-attachments-details.model';
export const CORRESPONDENCEDETAILATTACHMENTS: CorrespondenceAttachmentsDetail[] = [
    {
        actualRows: 3,
        filteredRows: 3,
        myRows: [
          {
            OwnerID: -2000,
            ParentID: 89031848,
            DataID: 89063481,
            Name: "2019-0008777-1.pdf",
            OriginOwnerID: 0,
            OriginDataID: 0,
            UserID: 275449,
            GroupID: 1001,
            UPermissions: 36995,
            GPermissions: 128,
            WPermissions: 128,
            SPermissions: 16777215,
            ACLCount: 13,
            PermID: null,
            DataType: null,
            CreatedBy: 275449,
            CreateDate: "2019/03/20 09:45:07",
            ModifiedBy: 275449,
            ModifyDate:" 2019/03/20 09:45:08",
            MaxVers: -1,
            Reserved: 0,
            ReservedBy: 0,
            ReservedDate: null,
            VersionNum: 1,
            DComment:" " ,
            DCategory: null,
            SubType: 144,
            ExAtt1: null,
            ExAtt2: null,
            Ordering: null,
            Major: null,
            Minor: null,
            ReleaseRef: null,
            ChildCount: 0,
            AssignedTo: null,
            DateAssigned: null,
            DateEffective: null,
            DateExpiration: null,
            DateDue: null,
            DateStarted: null,
            DateCompleted: null,
            Status: null,
            Priority: null,
            GIF: null,
            ExtendedData: "A<1,?>",
            Catalog: 0,
            CacheExpiration: 0,
            Deleted: 0,
            GUID: null,
            AttachementsDocCount: 3,
            AttachmentType:"../../assets/images/icons/pdf.svg",
            AttachmentSize: "1.5 mb",
            AttachmentUrl:"https://mannai.com/"
          },
          {
            OwnerID: -2000,
            ParentID: 89031848,
            DataID: 89061093,
            Name: "2019-0008777-1_attachment.zip",
            OriginOwnerID: 0,
            OriginDataID: 0,
            UserID: 275449,
            GroupID: 1001,
            UPermissions: 36995,
            GPermissions: 128,
            WPermissions: 128,
            SPermissions: 16777215,
            ACLCount: 13,
            PermID: null,
            DataType: null,
            CreatedBy: 275449,
            CreateDate: "2019/03/20 09:50:01",
            ModifiedBy: 275449,
            ModifyDate: "2019/03/20 09:50:16",
            MaxVers: -1,
            Reserved: 0,
            ReservedBy: 0,
            ReservedDate: null,
            VersionNum: 1,
            DComment: "",
            DCategory: null,
            SubType: 144,
            ExAtt1: null,
            ExAtt2: null,
            Ordering: null,
            Major: null,
            Minor: null,
            ReleaseRef: null,
            ChildCount: 0,
            AssignedTo: null,
            DateAssigned: null,
            DateEffective: null,
            DateExpiration: null,
            DateDue: null,
            DateStarted: null,
            DateCompleted: null,
            Status: null,
            Priority: null,
            GIF: null,
            ExtendedData: "A<1,?>" ,
            Catalog: 0,
            CacheExpiration: 0,
            Deleted: 0,
            GUID: null,
            AttachementsDocCount: 3,
            AttachmentType:"../../assets/images/icons/zip.svg",
            AttachmentSize: "50 kb",
            AttachmentUrl:"https://mannai.com/"
          },
          {
            OwnerID: -2000,
            ParentID: 89031848,
            DataID: 89063712,
            Name: "DN108-P02-HYD-PWA-TML-00071.zip",
            OriginOwnerID: 0,
            OriginDataID: 0,
            UserID: 275449,
            GroupID: 1001,
            UPermissions: 36995,
            GPermissions: 128,
            WPermissions: 128,
            SPermissions: 16777215,
            ACLCount: 13,
            PermID: null,
            DataType: null,
            CreatedBy: 275449,
            CreateDate: "2019/03/20 09:49:45",
            ModifiedBy: 275449,
            ModifyDate: "2019/03/20 09:49:55",
            MaxVers: -1,
            Reserved: 0,
            ReservedBy: 0,
            ReservedDate: null,
            VersionNum: 1,
            DComment: "" ,
            DCategory: null,
            SubType: 144,
            ExAtt1: null,
            ExAtt2: null,
            Ordering: null,
            Major: null,
            Minor: null,
            ReleaseRef: null,
            ChildCount: 0,
            AssignedTo: null,
            DateAssigned: null,
            DateEffective: null,
            DateExpiration: null,
            DateDue: null,
            DateStarted: null,
            DateCompleted: null,
            Status: null,
            Priority: null,
            GIF: null,
            ExtendedData: "A<1,?>",
            Catalog: 0,
            CacheExpiration: 0,
            Deleted: 0,
            GUID: null,
            AttachementsDocCount: 3,
            AttachmentType:"../../assets/images/icons/doc.svg",
            AttachmentSize: "2.1 mb",
            AttachmentUrl:"https://mannai.com/"
          }
        ],
        sourceID: 8043162,
        success: true,
        totalRows: 3,
        totalSourceRows: 3
      }
]
