import { CorrespondenceCollaborationDetail } from './correspondence-collaboration-details.model';
export const CORRESPONDENCEDETAILCOLLABORATION: CorrespondenceCollaborationDetail[] = [
    {   actualRows:1,
        filteredRows:1,
        myRows:[{
            VolumeID: 90214231,
            OrderNum: 1,
            SubSeq: 1,
            UserColl_User: 271930,
            UserColl_Type: "User",
            UserColl_Purpose: null,
            UserColl_Priority: null,
            UserColl_DueDate: null,
            UserColl_Notes: null,
            UserColl_FurtherAction: 1,
            UserColl_Status: null,
            UserColl_Disposition: null,
            Name_EN: "Bader Mohammed H A Darwish",
            Name_AR: "بدر محمد درويش",
            DepartmentName_EN: "Highway Projects Dept",
            DepartmentName_AR: "ادارة مشروعات الطرق السريعة",
            FurtherActions_EN: null,
            FurtherActions_AR: null,
            Purpose_EN: null,
            Purpose_AR: null,
            AttrSuffix:" 01",
            SubWorkTask_SubWorkID: 90214231,
            SubWorkTask_TaskID: 55,
            SubWorkTask_Title: "01.01 Correspondence Collaboration",
            SubWorkTask_Type: 1,
            SubWorkTask_Status: 2,
            SubWorkTask_Active: 1,
            Status_EN: "In Progress",
            Status_AR: "In Progress"
        },
        {
            VolumeID: 90214231,
            OrderNum: 1,
            SubSeq: 1,
            UserColl_User: 271930,
            UserColl_Type: "User",
            UserColl_Purpose: null,
            UserColl_Priority: null,
            UserColl_DueDate: null,
            UserColl_Notes: null,
            UserColl_FurtherAction: 1,
            UserColl_Status: null,
            UserColl_Disposition: null,
            Name_EN: "Bader Mohammed H A Darwish",
            Name_AR: "بدر محمد درويش",
            DepartmentName_EN: "Highway Projects Dept",
            DepartmentName_AR: "ادارة مشروعات الطرق السريعة",
            FurtherActions_EN: null,
            FurtherActions_AR: null,
            Purpose_EN: null,
            Purpose_AR: null,
            AttrSuffix:" 01",
            SubWorkTask_SubWorkID: 90214231,
            SubWorkTask_TaskID: 55,
            SubWorkTask_Title: "01.01 Correspondence Collaboration",
            SubWorkTask_Type: 1,
            SubWorkTask_Status: 2,
            SubWorkTask_Active: 1,
            Status_EN: "In Progress",
            Status_AR: "In Progress"
        },{
            VolumeID: 90214231,
            OrderNum: 1,
            SubSeq: 1,
            UserColl_User: 271930,
            UserColl_Type: "User",
            UserColl_Purpose: null,
            UserColl_Priority: null,
            UserColl_DueDate: null,
            UserColl_Notes: null,
            UserColl_FurtherAction: 1,
            UserColl_Status: null,
            UserColl_Disposition: null,
            Name_EN: "Bader Mohammed H A Darwish",
            Name_AR: "بدر محمد درويش",
            DepartmentName_EN: "Highway Projects Dept",
            DepartmentName_AR: "ادارة مشروعات الطرق السريعة",
            FurtherActions_EN: null,
            FurtherActions_AR: null,
            Purpose_EN: null,
            Purpose_AR: null,
            AttrSuffix:" 01",
            SubWorkTask_SubWorkID: 90214231,
            SubWorkTask_TaskID: 55,
            SubWorkTask_Title: "01.01 Correspondence Collaboration",
            SubWorkTask_Type: 1,
            SubWorkTask_Status: 2,
            SubWorkTask_Active: 1,
            Status_EN: "In Progress",
            Status_AR: "In Progress"
        }
    ],
        sourceID:8042764,
        success:true,
        totalRows:1,
        totalSourceRows:1
    }
]
