import { CorrespondenceCorrespondDetail } from './correspondence-details-correspondence.model';
export const CORRESPONDENCEDETAILCORRESPONDENCE: CorrespondenceCorrespondDetail[] = [
    {
        actualRows: 3,
        filteredRows: 3,
        myRows: [
          {
            VolumeID: 311308,
            DataID: 1,
            VersionNum: -1,
            Seq: 60,
            RowSeqNum: 1,
            IterationNum: 1,
            CorrespondenceDate: "2018/10/27 14:16:29",
            CoverDate: null,
            CorrespondenceStepDueDate: "2018/10/28 00:00:00",
            CorrespondenceDueDate: null,
            CorrespondenceSignatureDate: null,
            AcknowledgementDate: null,
            DispatchDate: null,
            ResponseDueDate: null,
            CorrespondenceFlowType: "7",
            CorrespondenceCode: null,
            CorrespondenceYear: "2018",
            ExternalOrganization: null,
            SenderID: 1,
            SenderUserID: 1000,
            SenderVersion: 1,
            SenderDepartment: 68,
            SenderSection: 71,
            SenderRole: null,
            SenderName: null,
            RecipientID: 0,
            RecipientUserID: 275254,
            RecipientVersion: 1,
            RecipientType: "Department",
            RecipientDepartment: 68,
            RecipientSection: null,
            RecipientRole: null,
            RecipientName: null,
            FinalRecipientID: null,
            FinalRecipientUserID: null,
            FinalRecipientVersion: null,
            FinalRecipientType: null,
            FinalRecipientDepartment: null,
            FinalRecipientSection: null,
            FinalRecipientRole: null,
            Advisor: null,
            SigningAuthority: 1000,
            SigningAuthoritySecretary: null,
            Confidential: 0,
            Priority: 1,
            CorrespondenceComments: null,
            HeadOfSection: null,
            HeadOfSectionSecretary: null,
            HeadOfSectionRequired: "No",
            IDNumber: null,
            DocumentNumber: null,
            BaseType: null,
            CorrespondenceType2: null,
            DocumentType: null,
            CompanyRegistrationNumber: null,
            RegisteredBy: null,
            CommitmentNumber: null,
            ArabicSubject: "Test CTS",
            EnglishSubject: "Test CTS",
            ProjectCode: null,
            BudgetNumber: null,
            TenderNumber: null,
            ContractNumber: null,
            StaffNumber: null,
            DeliveryStatus: null,
            FilingPlanYear: null,
            PhysicalLocation: null,
            FilingPlanCabinet: null,
            FilingPlanRow: null,
            FilingPlanShelf: null,
            FilingPlanFile: null,
            FilingPlanPath: null,
            TemplateLanguage: "EN",
            DispatchMethod: null,
            DispatchReference: null,
            CorrespondenceStatus: null,
            CoverID: 310763,
            CorrespondenceID: 310093,
            CorrespondenceArchive: 288911,
            Disposition1: "SendOn",
            Disposition2: null,
            Disposition3: "E1b",
            RejectReason: null,
            RejectReasonText: null,
            CorrespondencePhase: 2,
            MultipleSignatures: 0,
            ConnectedID: 0,
            ConnectedRefID: 0,
            CorrespondencePurpose: null,
            CorrespondenceNotificationFax: null,
            ExternalOrganizationFax: null,
            SkipDeptSecratory: 1,
            SkipHOSSecratory: 0,
            FinalRecipientName: null,
            FinalExternalOrganization: null
          }],
        sourceID: 8043162,
        success: true,
        totalRows: 3,
        totalSourceRows: 3
      }
]
