import { CorrespondenceCCDetail } from './correspondence-cc-details.model';
export const CORRESPONDENCEDETAILCOVER: CorrespondenceCCDetail[] = [
    {
        actualRows: 3,
        filteredRows: 3,
        myRows: [
          {
            OwnerID: -2000,
            ParentID: 89031848,
            DataID: 89063481,
            Name: "2019-0008777-1.pdf",
            OriginOwnerID: 0,
            OriginDataID: 0,
            UserID: 275449,
            GroupID: 1001,
            UPermissions: 36995,
            GPermissions: 128,
            WPermissions: 128,
            SPermissions: 16777215,
            ACLCount: 13,
            PermID: null,
            DataType: null,
            CreatedBy: 275449,
            CreateDate: "2019/03/20 09:45:07",
            ModifiedBy: 275449,
            ModifyDate: "2019/03/20 09:45:08",
            MaxVers: -1,
            Reserved: 0,
            ReservedBy: 0,
            ReservedDate: null,
            VersionNum: 1,
            DComment: "",
            DCategory: null,
            SubType: 144,
            ExAtt1: null,
            ExAtt2: null,
            Ordering: null,
            Major: null,
            Minor: null,
            ReleaseRef: null,
            ChildCount: 0,
            AssignedTo: null,
            DateAssigned: null,
            DateEffective: null,
            DateExpiration: null,
            DateDue: null,
            DateStarted: null,
            DateCompleted: null,
            Status: null,
            Priority: null,
            GIF: null,
            ExtendedData: "A<1,?>",
            Catalog: 0,
            CacheExpiration: 0,
            Deleted: 0,
            GUID: null,
            AttachementsDocCount: 3,
            CoverType:"../../assets/images/icons/pdf.svg",
            CoverSize: "50k",
            CoverUrl:"https://mannai.com/"
          }],
        sourceID: 8043162,
        success: true,
        totalRows: 3,
        totalSourceRows: 3
      }
]
