import { transferHistoryDetail } from './transfer-history-details.model';
export const TRANSFERHISTORYDETAILS: transferHistoryDetail[] = [
    {
        actualRows: 3,
        filteredRows: 3,
        myRows: [{
            ID: 187968,
            VolumeID: 72381519,
            TransferDate: '2018\/12\/23 10:34:04',
            OpenDate: '2018\/12\/23 10:37:51',
            AcknowledgedDate: '2019\/01\/30 12:45:07',
            CompletedDate: '2019\/01\/30 12:45:07',
            TransferType: 0,
            holdSecretaryID: 273106,
            onBehalfUserID: 8051404,
            TransferUserID: 8051404,
            StatusID: 1,
            Status: 'Completed',
            sDepartment_EN: 'Test Department 2',
            sDepartment_AR: 'Test Department 2',
            sName_EN: 'Secretary (DNDD)',
            sName_AR:' Secretary (DNDD)',
            sContact: null,
            rDepartment_EN: 'Information System Department, Development Section',
            rDepartment_AR: 'ادارة نظم المعلومات, قسم التطوير',
            rName_EN:' Mohamed Mohy Taha Aboushady',
            rName_AR: 'Mohamed Mohy AbouShady',
            rContact: 44950825,
            Purpose_EN:' For Action',
            Purpose_AR: 'أخرى',
            NotesComplete: '',
            TransferComment:' Annotation test'
          },
          {
            ID: 188003,
            VolumeID: 72381519,
            TransferDate: '2018\/12\/23 10:38:45',
            OpenDate: '2018\/12\/23 10:40:31',
            AcknowledgedDate: '2019\/01\/27 11:47:29',
            CompletedDate: null,
            TransferType: 0,
            holdSecretaryID: 8050964,
            onBehalfUserID: 8051404,
            TransferUserID: 8051404,
            StatusID: 1,
            Status: 'Completed',
            sDepartment_EN:' Test Department 2',
            sDepartment_AR: 'Test Department 2',
            sName_EN: 'Secretary (DNDD)',
            sName_AR:' Secretary (DNDD)',
            sContact: null,
            rDepartment_EN: 'Test Department 2',
            rDepartment_AR: 'Test Department 2',
            rName_EN: 'Signing Authority DNDD',
            rName_AR: 'Signing Authority DNDD',
            rContact: null,
            Purpose_EN: 'For Action',
            Purpose_AR: 'أخرى',
            NotesComplete:'' ,
            TransferComment: 'annotation testing'
          },
          {
            ID: 227689,
            VolumeID: 72381519,
            TransferDate: '2019\/01\/27 11:47:24',
            OpenDate:' 2019\/01\/27 11:48:56',
            AcknowledgedDate: null,
            CompletedDate: null,
            TransferType: 10,
            holdSecretaryID: 8051404,
            onBehalfUserID: 0,
            TransferUserID: 8050964,
            StatusID: 0,
            Status: 'New',
            sDepartment_EN:' Test Department 2',
            sDepartment_AR: 'Test Department 2',
            sName_EN: 'Signing Authority DNDD',
            sName_AR: 'Signing Authority DNDD',
            sContact: null,
            rDepartment_EN: 'Test Department 2',
            rDepartment_AR: 'Test Department 2',
            rName_EN: 'FCTS Structure Receiver',
            rName_AR:' FCTS Structure Receiver',
            rContact: null,
            Purpose_EN:' Draft outgoing letter',
            Purpose_AR:' إعادة إرسال',
            NotesComplete: null,
            TransferComment: 'aswini tranafered'
          },
          {
            ID: 227689,
            VolumeID: 72381519,
            TransferDate: '2019\/01\/27 11:47:24',
            OpenDate:' 2019\/01\/27 11:48:56',
            AcknowledgedDate: null,
            CompletedDate: null,
            TransferType: 10,
            holdSecretaryID: 8051404,
            onBehalfUserID: 0,
            TransferUserID: 8050964,
            StatusID: 0,
            Status: 'New',
            sDepartment_EN:' Test Department 2',
            sDepartment_AR: 'Test Department 2',
            sName_EN: 'Signing Authority DNDD',
            sName_AR: 'Signing Authority DNDD',
            sContact: null,
            rDepartment_EN: 'Test Department 2',
            rDepartment_AR: 'Test Department 2',
            rName_EN: 'FCTS Structure Receiver',
            rName_AR:' FCTS Structure Receiver',
            rContact: null,
            Purpose_EN:' Draft outgoing letter',
            Purpose_AR:' إعادة إرسال',
            NotesComplete: null,
            TransferComment: 'aswini tranafered'
          }],
        sourceID: 8043162,
        success: true,
        totalRows: 3,
        totalSourceRows: 3
      }
]
