import { TransferDetail } from './transfer-details.model';
export const TRANSFERDETAILS: TransferDetail[] = [
    {
        actualRows: 3,
        filteredRows: 3,
        myRows: [{
          ID: 187968,
          VolumeID: 72381519,
          UserID: 273106,
          TransferUserID: 8051404,
          Purpose: 9,
          DueDate: "2018\/12\/24 10:34:00",
          Notes: "",
          Status: 1,
          TransferType: 0,
          TransferDate: "2018\/12\/23 10:34:04",
          CompletedDate: "2019\/01\/30 12:45:07",
          NotesComplete: "",
          parentID: 0,
          PriorityID: 3,
          isReplay: 0,
          completeUserID: 273106,
          onBehalfUserID: 8051404,
          holdSecretaryID: 273106,
          AcceptedDate: null,
          WasOpened: 1 ,
          OpenDate:" 2018\/12\/23 10:37:51",
          OpenUserID: 273106,
          AcknowledgedDate: "2019\/01\/30 12:45:07",
          AcknowledgedUserID: 273106,
          sName_EN:" Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print",
          sName_AR:" Secretary (DNDD)",
          rName_EN:" Mohamed Mohy Taha Aboushady",
          rName_AR: "Mohamed Mohy AbouShady",
          rRoleName_EN: "Planning & Follow Up Researcher - 2",
          rRoleName_AR: "Planning & Follow Up Researcher - 2",
          sRoleName_EN: "Secretary - 3",
          sRoleName_AR:" Secretary - 3",
          Purpose_EN: "For Action",
          Purpose_AR: "أخرى"
          }],
        sourceID: 8043162,
        success: true,
        totalRows: 3,
        totalSourceRows: 3
      }
]
