import { workflowHistoryDetail } from './workflow-history-details.model';
export const WORKFLOWHISTORYDETAILS: workflowHistoryDetail[] = [
    {
        actualRows: 3,
        filteredRows: 3,
        myRows: [{
          WF_Title: "2019\/0002211\/7 - Internal",
          Action_Date: "2019\/02\/05 15:03:05",
          Step:"08 CC Correspondence",
          Action: "Acknowledged",
          Performer:" FCTS_SR_414",
          PerformerName_EN: "FCTS_SR_414",
          PerformerName_AR: "FCTS_SR_414",
          MapTask_SubType: 110,
          SubWorkTask_Status: 0,
          WorkAudit_Status: 0,
          ComboName: "External Highways Section - FCTS Structure Receiver",
          DepartmentName_EN: null,
          DepartmentName_AR: null,
          SectionName_EN: null,
          SectionName_AR: null,
          Contact: null,
          SubWorkTask_PerformerID: 66835022,
          Comment: null,
          Disposition: null
          },
          {
          WF_Title: "2019\/0002211\/7 - Internal",
          Action_Date: "2019\/02\/05 15:03:05",
          Step: "08 CC Correspondence",
          Action: "Acknowledged",
          Performer:" FCTS_SR_414",
          PerformerName_EN: "FCTS_SR_414",
          PerformerName_AR: "FCTS_SR_414",
          MapTask_SubType: 110,
          SubWorkTask_Status: 0,
          WorkAudit_Status: 0,
          ComboName: "External Highways Section - FCTS Structure Receiver",
          DepartmentName_EN: null,
          DepartmentName_AR: null,
          SectionName_EN: null,
          SectionName_AR: null,
          Contact: null,
          SubWorkTask_PerformerID: 66835022,
          Comment: null,
          Disposition: null
          },
          {
          WF_Title: "2019\/0002211\/7 - Internal",
          Action_Date: "2019\/02\/05 15:03:05",
          Step:" 08 CC Correspondence",
          Action: "Acknowledged",
          Performer:" FCTS_SR_414",
          PerformerName_EN: "FCTS_SR_414",
          PerformerName_AR: "FCTS_SR_414",
          MapTask_SubType: 110,
          SubWorkTask_Status: 0,
          WorkAudit_Status: 0,
          ComboName: "External Highways Section - FCTS Structure Receiver",
          DepartmentName_EN: null,
          DepartmentName_AR: null,
          SectionName_EN: null,
          SectionName_AR: null,
          Contact: null,
          SubWorkTask_PerformerID: 66835022,
          Comment: null,
          Disposition: null
          },
          {
          WF_Title: "2019\/0002211\/7 - Internal",
          Action_Date: "2019\/02\/05 15:03:05",
          Step:" 08 CC Correspondence",
          Action: "Acknowledged",
          Performer:" FCTS_SR_414",
          PerformerName_EN: "FCTS_SR_414",
          PerformerName_AR: "FCTS_SR_414",
          MapTask_SubType: 110,
          SubWorkTask_Status: 0,
          WorkAudit_Status: 0,
          ComboName: "External Highways Section - FCTS Structure Receiver",
          DepartmentName_EN: null,
          DepartmentName_AR: null,
          SectionName_EN: null,
          SectionName_AR: null,
          Contact: null,
          SubWorkTask_PerformerID: 66835022,
          Comment: null,
          Disposition: null
          }],
        sourceID: 8043162,
        success: true,
        totalRows: 3,
        totalSourceRows: 3
      }
]
